{
 "title": "Locust",
 "description": "Locust Exporter",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info{namespace=~\"online-boutique.*\"}, namespace)"
    }
   },
   {
    "name": "type",
    "query": {
     "query": "label_values(namespace_workload_pod:kube_pod_owner:relabel{namespace=~\"$namespace\", workload=~\".+\"}, workload_type)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Locust Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "locust_running", "legendFormat": "{{ namespace }}" }
   ]
  },
  {
   "title": "Swarmed users",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "locust_users" }
   ]
  },
  {
   "title": "Running Pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Running\",namespace=\"online-boutique\"})by(phase)",
     "legendFormat": "{{ phase }}"
    }
   ]
  },
  {
   "title": "Crashing Pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Failed\"})"
    }
   ]
  },
  {
   "title": "Pending Pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Pending\",namespace=\"online-boutique\"})"
    }
   ]
  },
  {
   "title": "Current RPS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "locust_requests_current_rps{name=\"Aggregated\"}"
    }
   ]
  },
  {
   "title": "Current success ratio",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(locust_requests_current_rps{name=\"Aggregated\"} - locust_requests_current_fail_per_sec{name=\"Aggregated\"}) / locust_requests_current_rps{name=\"Aggregated\"}"
    }
   ]
  },
  {
   "title": "Current failure ratio",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "1 - ((locust_requests_current_rps{name=\"Aggregated\"} - locust_requests_current_fail_per_sec{name=\"Aggregated\",}) / locust_requests_current_rps{name=\"Aggregated\"})"
    }
   ]
  },
  {
   "title": "Liqo Gateway Traffic",
   "type": "graph",
   "description": "Bytes transmitted/received over the network by the container per second in the last minute",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{pod=~\"liqo-gateway-.*\",interface=~\"liqo.host\"}[1m]))",
     "legendFormat": "Transmit {{ interface }}"
    },
    {
     "expr": "sum(rate(container_network_receive_bytes_total{pod=~\"liqo-gateway-.*\",interface=~\"liqo.host\"}[1m]))",
     "legendFormat": "Received"
    }
   ]
  },
  {
   "title": "CPU request % per node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\",node=~\"liqo-.*\"}) by (node)/sum(kube_node_status_allocatable{node=~\"liqo-.*\",resource=\"cpu\"}) by (node)*100",
     "legendFormat": "{{ node }}"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\",node=~\"cluster4-.*\"}) by (node)/sum(kube_node_status_allocatable{node=~\"cluster4-.*\",resource=\"cpu\"}) by (node)*100",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - ((locust_requests_current_rps{name=\"Aggregated\"} - locust_requests_current_fail_per_sec{name=\"Aggregated\"}) / locust_requests_current_rps{name=\"Aggregated\"})",
     "legendFormat": "Error Rate"
    }
   ]
  },
  {
   "title": "Response Times",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 10 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "locust_requests_current_response_time_percentile_95",
     "legendFormat": "P95"
    },
    {
     "expr": "locust_requests_current_response_time_percentile_50",
     "legendFormat": "P50"
    },
    { "expr": "6000", "legendFormat": "SLO" }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"liqo\", pod=~\"liqo-gateway-.*\"}) by (container)"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 18 },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"liqo\", pod=~\"liqo-gateway-.*\", container!=\"\", image!=\"\"}) by (container)"
    }
   ]
  }
 ]
}