---
apiVersion: split.smi-spec.io/v1alpha1
kind: TrafficSplit
metadata:
  name: emailservice
spec:
  service: emailservice
  backends:
  - service: emailservice
    weight: 50
  - service: emailservice-west
    weight: 50
---
kind: TrafficSplit
metadata:
  name: recommendationservice
spec:
  service: recommendationservice
  backends:
  - service: recommendationservice
    weight: 50
  - service: recommendationservice-west
    weight: 50
---
kind: TrafficSplit
metadata:
  name: frontend
spec:
  service: frontend
  backends:
  - service: frontend
    weight: 50
  - service: frontend-west
    weight: 50
---
kind: TrafficSplit
metadata:
  name: frontend-external
spec:
  service: frontend-external
  backends:
  - service: frontend-external
    weight: 50
  - service: frontend-external-west
    weight: 50
---
kind: TrafficSplit
metadata:
  name: productcatalogservice
spec:
  service: productcatalogservice
  backends:
  - service: productcatalogservice
    weight: 50
  - service: productcatalogservice-west
    weight: 50
---
kind: TrafficSplit
metadata:
  name: currencyservice
spec:
  service: currencyservice
  backends:
  - service: currencyservice
    weight: 50
  - service: currencyservice-west
    weight: 50
---
kind: TrafficSplit
metadata:
  name: redis-cart
spec:
  service: redis-cart
  backends:
  - service: redis-cart
    weight: 50
  - service: redis-cart-west
    weight: 50
---