#!/bin/bash

NS="default"
N=-1
NCONTEXT=none
declare -a contexts

i=0
while [[ i -lt $# ]]; do
  i=$((i+1))
  FLAG="$(cut -d ' ' -f $i <<< $@)"
  i=$((i+1))
  FVALUE="$(cut -d ' ' -f $i <<< $@)" 
  i=$((i+1))
  echo -e "[i] Parse ${FLAG} ${FVALUE}"
  case $FLAG in
    "-i" | "--incremental")
      i=$((i-2))
      N=1
    ;;
    "-ns" | "--namespace")
      NS=$FVALUE
    ;;
    "--contexts")
      i=$((i-2))

      echo "Insert the number of contexts: "
      read NCONTEXT

      j=0
      while [[ j -lt NCONTEXT ]]
      do
        echo "Insert the name of the context: "
        read contexts[j]
        j=$((j+1))
      done
      echo "All contexts: ${contexts[@]}"
    ;;
    "-h" | "--help")
      echo -e "This is a custom scraper for the Liqo Benchmark\n"
      echo "Usage:"
      echo -e "./custom_scraper [flags]\n"
      echo "Flags:"
      echo -e "\t-i\t--incremental\t\t\tAdd an incremental number when the script store the data"
      echo -e "\t-ns\t--namespace\t\t\tNamespace of the application"
      echo -e "\t--contexts\t\t\tEnable multi-context"

      exit 1;
    ;;
    *)
      echo "not found"
    ;;
  esac
done

mkdir -p metrics

while true
do
  echo "$(date)"
  _date=$(date +%s)
  prefix=""
  if [[ $N -gt 0 ]]
  then
    prefix="${N}_"
    N=$((N+1))
  fi

  echo "[i] curl -o ./metrics/$nameFile http://127.0.0.1:9646/metrics"
  nameFile="${prefix}locust_exporter_${_date}.logs"
  curl -o ./metrics/$nameFile http://127.0.0.1:9646/metrics

  nameFile="${prefix}deploy_${_date}.logs"

  if [[ "$NCONTEXT" != "none" ]]
  then
    result=""
    j=0
    while [[ j -lt NCONTEXT ]]
    do
      echo "[i] kubectl get deploy -n $NS --context=${contexts[$j]}"
      result="$result$(kubectl get deploy -n $NS --context=${contexts[$j]})"
      j=$((j+1))
    done
    echo $result > ./metrics/$nameFile
  else
    result=$(kubectl get deploy -n $NS)

    if [[ "$result" == "" ]]
    then
      echo "[i] No deploy resources found"
    else
      echo $result > ./metrics/$nameFile
    fi
  fi

  nameFile="${prefix}hpa_${_date}.logs"

  if [[ "$NCONTEXT" != "none" ]]
  then
    result=""
    j=0
    while [[ j -lt NCONTEXT ]]
    do
      echo "[i] kubectl get hpa -n $NS --context=${contexts[$j]}"
      result="$result$(kubectl get hpa -n $NS --context=${contexts[$j]})"
      j=$((j+1))
    done
    echo $result > ./metrics/$nameFile
  else
    result=$(kubectl get hpa -n $NS)

    if [[ "$result" == "" ]]
    then
      echo "[i] No hpa resources found"
    else
      echo $result > ./metrics/$nameFile
    fi
  fi

  nameFile="${prefix}uptime_${_date}.logs"
  result=$(uptime)
  echo $result > ./metrics/$nameFile

  sleep 5

done
