---
apiVersion: split.smi-spec.io/v1alpha1
kind: TrafficSplit
metadata:
  name: checkoutservice
spec:
  service: checkoutservice
  backends:
  #- service: checkoutservice
  #  weight: 100
  - service: checkoutservice-east
    weight: 100
---
apiVersion: split.smi-spec.io/v1alpha1
kind: TrafficSplit
metadata:
  name: paymentservice
spec:
  service: paymentservice
  backends:
  #- service: paymentservice
  #  weight: 100
  - service: paymentservice-east
    weight: 100
---
apiVersion: split.smi-spec.io/v1alpha1
kind: TrafficSplit
metadata:
  name: cartservice
spec:
  service: cartservice
  backends:
  #- service: cartservice
  #  weight: 100
  - service: cartservice-east
    weight: 100
---
apiVersion: split.smi-spec.io/v1alpha1
kind: TrafficSplit
metadata:
  name: shippingservice
spec:
  service: shippingservice
  backends:
  #- service: shippingservice
  #  weight: 100
  - service: shippingservice-east
    weight: 100
---
apiVersion: split.smi-spec.io/v1alpha1
kind: TrafficSplit
metadata:
  name: adservice
spec:
  service: adservice
  backends:
  #- service: adservice
  #  weight: 100
  - service: adservice-east
    weight: 100
---